### ISSUE TITLE
Add new parameters to ucm()

### ISSUE THREAD

**Issue by timvink** [kaushikrch/rucm#10]
I would like to add two new parameters to the `ucm()` function. Specifically: 

- `tol`. A tolerance parameter for SSModel on line https://github.com/kaushikrch/rucm/blob/master/R/ucm.R#L112
- `method`. The method used by `fitSSM()` on line https://github.com/kaushikrch/rucm/blob/master/R/ucm.R#L114

Not sure if package is still maintained.. if I make a merge request, will someone review it?

**Comment by kaushikrch** [comment]
Yes, please go ahead. The codes can be reviewed.

**Comment by timvink** [comment]
Great, here's the MR: https://github.com/kaushikrch/rucm/pull/11
