### ISSUE TITLE
Not able to use independent variables in predict.UCM

### ISSUE THREAD

**Issue by Nawaz91** [kaushikrch/rucm#2]
Have a couple of regressors that i am able to fit a UCM model on. But not able to predict the response variable using the future values of these regressors. When will this be up and running in predict.UCM?

**Comment by kaushikrch** [comment]
@Nawaz91 here is a way out from the bug using package KFAS:
- Fit a ucm model.
  `fit_train_ucm <- ucm(...)`
- Replicate NA's for the number of rows of forecasting data using parameters from the old model.
  `newdata <- SSModel(rep(NA,nrow(<name where independents are stored>)) ~ x + SSMtrend(2, Q = list(fit_train_ucm$est.var.level, fit_train_ucm$est.var.slope)) + SSMseasonal(12, Q = fit_train_ucm$est.var.season), H = fit_train_ucm$irr.var, data=<name where independents are stored>)`
- Depending upon whether you have seasonality and cyclicity change the code, if you only have level and no slope then `SSMtrend(1, Q = fit_train_ucm$est.var.level)`
- Go on using the predict function
  `pred<-predict(fit_train_ucm$model, newdata=newdata)`

**Comment by kaushikrch** [comment]
I will commit a version of rucm with changes over the weekend.
