### ISSUE TITLE
How to find confidence interval of the predictions?

### ISSUE THREAD

**Issue by amritnm** [kaushikrch/rucm#9]
I am not very much thorough with the UCM methodology but the results seem to be at par or better than seasonal ARIMA models in my dataset. But to compare the results, I need to have mse, rmse, mape etc. which I usually get in output of ARIMA models in R. In SAS, I have seen the output of proc ucm giving such confidence intervals. 
1. Is there a way I can find the confidence intervals of predictions in R.
2. Is there a way I can calculate the rmse and other metrics, ie, how do I make predictions in backdates? Or for the dates involving modeling data.

**Comment by kaushikrch** [comment]
@amritnm I am closing this issue as this is actually not an issue. You should not compare the output of proc ucm of SAS with that of R as R uses S3 objects for reporting the objects.

You can print the ucm model and look at the p-values and then calculate the confidence intervals by back-calculation. You can look at the `print.ucm` function of how estimates and standard errors may be printed. 
You can save the predictions of ucm model using the `predict` function and compare it with dependent variable to calculate the standard metrics of model fit.
